
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwnyotnopqbynarbtpsf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3bnlvdG5vcHFieW5hcmJ0cHNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwNjUzNjIsImV4cCI6MjA1NDY0MTM2Mn0.mQ_lZWI5l4BbaEvZ_xcszbsJPLkE7gzG2TY28oRt3Uw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
